name: firefox
on: push
env:
  PROXY: proxy.crawlera.com:8011
  URL: https://httpbin.scrapinghub.com/ip
  KEY: ${{secrets.KEY}}
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: firefox
        run: make firefox
