name: php-7
on: push
env:
  PROXY: proxy.crawlera.com:8010
  URL: https://httpbin.scrapinghub.com/ip
  KEY: ${{secrets.KEY}}
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make $GITHUB_WORKFLOW
