name: py-scrapy
on: push
env:
  PROXY: proxy.zyte.com:8010
  KEY: ${{secrets.KEY}}
  URL: https://httpbin.scrapinghub.com/ip
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make $GITHUB_WORKFLOW
